### ISSUE TITLE
Tixi/Tigl issue with Python 3.8

### ISSUE THREAD

**Issue by joergbrech** [DLR-SC/tigl-conda#17]
For some reason, I get a library architecture mismatch if I try to install tigl3 into a Miniforge environment with Python 3.8 (`conda create -n test tigl3 -c dlr-sc`):

<details>
<summary>conda list output</summary>

```
(test) C:\>conda list
# packages in environment at C:\ProgramData\Miniforge3\envs\test:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.5.30            h5b45459_0    conda-forge
certifi                   2021.5.30        py38haa244fe_0    conda-forge
freeimageplus             3.18.0               h6538335_2    dlr-sc
freetype                  2.6.5                hfa6e2cd_4    dlr-sc
icu                       68.1                 h0e60522_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
opencascade               7.4.0                h7e01d4e_7    dlr-sc
openssl                   1.1.1k               h8ffe710_0    conda-forge
pip                       21.2.2             pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
python                    3.8.10          h7840368_1_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pythonocc-core            7.4.1            py38h7e01d4e_3    dlr-sc
qt                        5.12.9               h5909a2a_4    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h8ffe710_0    conda-forge
tbb                       2019.5               h7e01d4e_1    dlr-sc
tigl3                     3.2.0            py38h7e01d4e_1    dlr-sc
tixi3                     3.1.1            py38h9d197f5_2    dlr-sc
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge

(test) C:\>python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tigl3 import tigl3wrapper
Traceback (most recent call last):
  File "C:\ProgramData\Miniforge3\envs\test\lib\site-packages\tigl3\tigl3wrapper.py", line 306, in Tigl3
    lib = ctypes.cdll.tigl3
  File "C:\ProgramData\Miniforge3\envs\test\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\ProgramData\Miniforge3\envs\test\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'tigl3' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniforge3\envs\test\lib\site-packages\tigl3\tigl3wrapper.py", line 297, in <module>
    class Tigl3(object):
  File "C:\ProgramData\Miniforge3\envs\test\lib\site-packages\tigl3\tigl3wrapper.py", line 312, in Tigl3
    raise Exception("Could not load the tigl3 library. Please check if:\n" +
Exception: Could not load the tigl3 library. Please check if:
  1) The PATH (Windows) / LD_LIBRARY_PATH (Linux) environment variable points to the library
  2) The architecture of the library matches the architecture of python (a 32 bit python needs a 32 bit shared library)
```

</details>

```
(test) C:\>python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tigl3 import tigl3wrapper
Traceback (most recent call last):
  File "C:\ProgramData\Miniforge3\envs\test\lib\site-packages\tigl3\tigl3wrapper.py", line 306, in Tigl3
    lib = ctypes.cdll.tigl3
  File "C:\ProgramData\Miniforge3\envs\test\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\ProgramData\Miniforge3\envs\test\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'tigl3' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniforge3\envs\test\lib\site-packages\tigl3\tigl3wrapper.py", line 297, in <module>
    class Tigl3(object):
  File "C:\ProgramData\Miniforge3\envs\test\lib\site-packages\tigl3\tigl3wrapper.py", line 312, in Tigl3
    raise Exception("Could not load the tigl3 library. Please check if:\n" +
Exception: Could not load the tigl3 library. Please check if:
  1) The PATH (Windows) / LD_LIBRARY_PATH (Linux) environment variable points to the library
  2) The architecture of the library matches the architecture of python (a 32 bit python needs a 32 bit shared library)
```

In the same Miniforge installation, it works if I use python 3.7 (`conda create -n tigl3 python=3.7 tigl3 -c dlr-sc`):

<details>
<summary>conda list</summary>

```
(tigl3) C:\>conda list output
# packages in environment at C:\ProgramData\Miniforge3\envs\tigl3:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.5.30            h5b45459_0    conda-forge
certifi                   2021.5.30        py37h03978a9_0    conda-forge
freeimageplus             3.18.0               h6538335_2    dlr-sc
freetype                  2.6.5                hfa6e2cd_4    dlr-sc
icu                       68.1                 h0e60522_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
opencascade               7.4.0                h7e01d4e_7    dlr-sc
openssl                   1.1.1k               h8ffe710_0    conda-forge
pip                       21.2.2             pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py37h03978a9_7    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge
pyqtchart                 5.12             py37hf2a7229_7    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge
python                    3.7.10          h7840368_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pythonocc-core            7.4.1            py37h7e01d4e_3    dlr-sc
qt                        5.12.9               h5909a2a_4    conda-forge
setuptools                49.6.0           py37h03978a9_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h8ffe710_0    conda-forge
tbb                       2019.5               h7e01d4e_1    dlr-sc
tigl3                     3.2.0            py37h7e01d4e_1    dlr-sc
tixi3                     3.1.1            py37h9d197f5_2    dlr-sc
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge

```

</details>

```
(tigl3) C:\>python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tigl3 import tigl3wrapper
>>>
```

The same problem occurs for tixi.

**Comment by joergbrech** [comment]
DLR-SC/tixi#188 solves this for tixi3

**Comment by joergbrech** [comment]
DLR-SC/tigl#843 solves this for tigl3

**Comment by joergbrech** [comment]
I will close this issue here, because it is an isue of the bindings generators for tixi and tigl and not the conda configuration.
